export const data = [
  {
    img: "https://res.cloudinary.com/dzhhpr7f1/image/upload/v1749082728/834e6d30-7155-40a8-b259-82a48f9e4c39_tbzsoa.jpg",
    title: "Plan less, Explore More.",
    description:
      "Tired of juggling maps, notes, and bookings? Our app brings everything together in one place-smart, simple, and stress-free.",
  },
  {
    img: "https://res.cloudinary.com/dzhhpr7f1/image/upload/v1749082729/43a82e3d-911d-4ff7-bdbf-02778db5ee23_ycmycv.jpg",
    title: "Personalized itineraries on the go",
    description:
      "Create custom travel plans in minutes, get real-time suggestions, and easily adapt your schedule anytime. no WiFi? No problem.",
  },
  {
    img: "https://res.cloudinary.com/dzhhpr7f1/image/upload/v1749082729/97af5199-ac68-4297-a91e-b872d4ce7bf6_z0pess.jpg",
    title: "Travel Smarter",
    description:
      "We guide ou through every step with curated tips, local insights, and safety features- so you always feel prepared, even far from home.",
  },
];

export const Recommendation = [
  {
    id: 1,
    city: "bankok",
    country: "thailand",
    stars: 5,
    about:
      "Bangkok, the capital of Thailand, is a dynamic metropolis known for its golden temples, vibrant street life, and bustling markets. From the grandeur of the Grand Palace to the charm of riverside food stalls, it offers a fascinating blend of ancient tradition and modern energy.",
    temperature: "75",
    reviews: "156",
    img: "https://res.cloudinary.com/dzhhpr7f1/image/upload/v1749179589/IMG_2770_qokkoc.jpg",
    promo: false,
  },
  {
    id: 2,
    city: "tokyo",
    country: "japan",
    stars: 4,
    about:
      "japan is an island country in east asia, Located in the pacific ocean of the northeast coast of the asian mainland, it is boarded on the west by the sea of japan.",
    temperature: "67",
    reviews: "123",
    img: "https://res.cloudinary.com/dzhhpr7f1/image/upload/v1749180303/62d2b7fd-d63d-4d0e-8d7b-8da6511db27d_yikpjd.jpg",
    promo: false,
  },
  {
    id: 3,
    city: "panama",
    country: "thailand",
    stars: 4,
    about:
      "Panama is a culturally rich country where modern skyscrapers meet lush rainforests and historic colonial towns. Best known for the engineering marvel of the Panama Canal, it also boasts diverse wildlife, tropical beaches, and a unique fusion of Latin American and Caribbean influences.",
    temperature: "97",
    reviews: "142",
    img: "https://res.cloudinary.com/dzhhpr7f1/image/upload/v1749239632/5dffb1e4-9c79-484b-b938-83aa66adea2c_vbl2gm.jpg",
    promo: true,
  },
  {
    id: 4,
    city: "bali",
    country: "thailand",
    stars: 3,
    about:
      "Bali is a picturesque island paradise in Indonesia, famous for its stunning beaches, terraced rice fields, and spiritual atmosphere. With its ancient temples, traditional arts, and vibrant cultural festivals, Bali offers a serene escape that blends natural beauty with deep-rooted tradition.",
    temperature: "97",
    reviews: "213",
    img: "https://res.cloudinary.com/dzhhpr7f1/image/upload/v1749179675/fe72109e-632e-4cc1-8070-8aa0b16d0816_gqresr.jpg",
    promo: false,
  },
];

export const categories = [
  {
    name: "beach",
    img: "https://res.cloudinary.com/dzhhpr7f1/image/upload/v1749179677/d6268e25-bfdb-40e9-baeb-0dd25184ac4e_kofwlx.jpg",
  },
  {
    name: "resort",
    img: "https://res.cloudinary.com/dzhhpr7f1/image/upload/v1749179676/28eb38c3-ddfe-4e54-960a-08cf51c1419b_nefqyi.jpg",
  },
];

export const list = [
  "most visited",
  "cheapest",
  "closest to me",
  "adventurous",
  "urban",
  "high life",
  "remote",
];

export const flight = [
  {
    id: 1,
    airline: "run airway",
    from: "abuja",
    to: "bankok",
    date: "25 June 2025",
    departureTime: "06:15",
    arivalTime: "10:45",
    cheap: true,
    price: "1,300",
  },
  {
    id: 2,
    airline: "air peace",
    from: "lagos",
    to: "bali",
    date: "02 July 2025",
    departureTime: "12:30",
    arivalTime: "13:45",
    cheap: false,
    price: "2,500",
  },
  {
    id: 3,
    airline: "air peace",
    from: "lagos",
    to: "bali",
    date: "25 June 2025",
    departureTime: "05:00",
    arivalTime: "09:00",
    cheap: true,
    price: "2,250",
  },
  {
    id: 4,
    airline: "air dump",
    from: "abuja",
    to: "tokyo",
    date: "02 July 2025",
    departureTime: "04:15",
    arivalTime: "08:15",
    cheap: false,
    price: "3,100",
  },
  {
    id: 5,
    airline: "run airway",
    from: "abuja",
    to: "bali",
    date: "25 June 2025",
    departureTime: "04:15",
    arivalTime: "06:45",
    cheap: true,
    price: "1,300",
  },
  {
    id: 6,
    airline: "air peace",
    from: "lagos",
    to: "panama",
    date: "02 July 2025",
    departureTime: "19:30",
    arivalTime: "20:45",
    cheap: false,
    price: "2,250",
  },
  {
    id: 7,
    airline: "air peace",
    from: "abuja",
    to: "panama",
    date: "25 June 2025",
    departureTime: "00:15",
    arivalTime: "04:15",
    cheap: true,
    price: "3,100",
  },
  {
    id: 8,
    airline: "run airway",
    from: "abuja",
    to: "bali",
    date: "02 July 2025",
    departureTime: "22:30",
    arivalTime: "00:00",
    cheap: false,
    price: "3,100",
  },
  {
    id: 9,
    airline: "run airway",
    from: "lagos",
    to: "panama",
    date: "25 June 2025",
    departureTime: "18:30",
    arivalTime: "23:45",
    cheap: true,
    price: "2,250",
  },
  {
    id: 10,
    airline: "run airway",
    from: "abuja",
    to: "panama",
    date: "02 July 2025",
    departureTime: "10:30",
    arivalTime: "13:00",
    cheap: false,
    price: "2,500",
  },
  {
    id: 11,
    airline: "air dump",
    from: "lagos",
    to: "bali",
    date: "25 June 2025",
    departureTime: "11:00",
    arivalTime: "14:15",
    cheap: true,
    price: "4,300",
  },
  {
    id: 12,
    airline: "air dump",
    from: "lagos",
    to: "bankok",
    date: "02 July 2025",
    departureTime: "14:30",
    arivalTime: "15:30",
    cheap: false,
    price: "2,250",
  },
  {
    id: 13,
    airline: "air peace",
    from: "abuja",
    to: "bankok",
    date: "25 June 2025",
    departureTime: "13:15",
    arivalTime: "18:30",
    cheap: true,
    price: "4,300",
  },
  {
    id: 14,
    airline: "air dump",
    from: "abuja",
    to: "bankok",
    date: "02 July 2025",
    departureTime: "09:30",
    arivalTime: "13:45",
    cheap: false,
    price: "2,250",
  },
  {
    id: 15,
    airline: "run airway",
    from: "lagos",
    to: "bali",
    date: "25 June 2025",
    departureTime: "17:30",
    arivalTime: "21:30",
    cheap: true,
    price: "3,100",
  },
  {
    id: 16,
    airline: "air peace",
    from: "lagos",
    to: "panama",
    date: "02 July 2025",
    departureTime: "14:15",
    arivalTime: "15:45",
    cheap: false,
    price: "3,100",
  },
  {
    id: 17,
    airline: "air peace",
    from: "abuja",
    to: "tokyo",
    date: "25 June 2025",
    departureTime: "00:45",
    arivalTime: "01:00",
    cheap: true,
    price: "2,250",
  },
  {
    id: 18,
    airline: "air dump",
    from: "lagos",
    to: "tokyo",
    date: "02 July 2025",
    departureTime: "03:00",
    arivalTime: "04:30",
    cheap: false,
    price: "1,695",
  },
  {
    id: 19,
    airline: "air peace",
    from: "abuja",
    to: "bali",
    date: "25 June 2025",
    departureTime: "07:00",
    arivalTime: "09:00",
    cheap: true,
    price: "1,695",
  },
  {
    id: 20,
    airline: "run airway",
    from: "abuja",
    to: "bankok",
    date: "02 July 2025",
    departureTime: "18:30",
    arivalTime: "19:00",
    cheap: false,
    price: "3,100",
  },
  {
    id: 21,
    airline: "air peace",
    from: "abuja",
    to: "tokyo",
    date: "25 June 2025",
    departureTime: "19:30",
    arivalTime: "00:00",
    cheap: true,
    price: "2,500",
  },
  {
    id: 22,
    airline: "air peace",
    from: "abuja",
    to: "panama",
    date: "02 July 2025",
    departureTime: "17:00",
    arivalTime: "21:00",
    cheap: false,
    price: "1,300",
  },
  {
    id: 23,
    airline: "air peace",
    from: "abuja",
    to: "bankok",
    date: "25 June 2025",
    departureTime: "00:00",
    arivalTime: "04:15",
    cheap: true,
    price: "4,300",
  },
  {
    id: 24,
    airline: "air dump",
    from: "abuja",
    to: "tokyo",
    date: "02 July 2025",
    departureTime: "18:45",
    arivalTime: "20:45",
    cheap: false,
    price: "1,300",
  },
  {
    id: 25,
    airline: "run airway",
    from: "lagos",
    to: "tokyo",
    date: "25 June 2025",
    departureTime: "14:00",
    arivalTime: "18:00",
    cheap: true,
    price: "1,695",
  },
  {
    id: 26,
    airline: "run airway",
    from: "abuja",
    to: "tokyo",
    date: "02 July 2025",
    departureTime: "10:45",
    arivalTime: "12:00",
    cheap: false,
    price: "2,500",
  },
  {
    id: 27,
    airline: "run airway",
    from: "lagos",
    to: "tokyo",
    date: "25 June 2025",
    departureTime: "21:30",
    arivalTime: "23:30",
    cheap: true,
    price: "1,695",
  },
  {
    id: 28,
    airline: "air peace",
    from: "abuja",
    to: "bali",
    date: "02 July 2025",
    departureTime: "12:15",
    arivalTime: "15:30",
    cheap: false,
    price: "2,250",
  },
  {
    id: 29,
    airline: "air peace",
    from: "abuja",
    to: "bankok",
    date: "25 June 2025",
    departureTime: "06:00",
    arivalTime: "10:00",
    cheap: true,
    price: "4,300",
  },
  {
    id: 30,
    airline: "run airway",
    from: "abuja",
    to: "tokyo",
    date: "02 July 2025",
    departureTime: "01:00",
    arivalTime: "05:00",
    cheap: false,
    price: "4,300",
  },
  {
    id: 31,
    airline: "air peace",
    from: "lagos",
    to: "bankok",
    date: "25 June 2025",
    departureTime: "04:45",
    arivalTime: "09:15",
    cheap: true,
    price: "3,100",
  },
  {
    id: 32,
    airline: "air dump",
    from: "abuja",
    to: "bankok",
    date: "02 July 2025",
    departureTime: "20:00",
    arivalTime: "21:30",
    cheap: false,
    price: "3,100",
  },
  {
    id: 33,
    airline: "run airway",
    from: "abuja",
    to: "bankok",
    date: "25 June 2025",
    departureTime: "12:00",
    arivalTime: "15:30",
    cheap: true,
    price: "1,695",
  },
  {
    id: 34,
    airline: "run airway",
    from: "lagos",
    to: "bankok",
    date: "02 July 2025",
    departureTime: "05:00",
    arivalTime: "06:00",
    cheap: false,
    price: "2,250",
  },
  {
    id: 35,
    airline: "run airway",
    from: "abuja",
    to: "bankok",
    date: "25 June 2025",
    departureTime: "19:30",
    arivalTime: "00:45",
    cheap: true,
    price: "1,300",
  },
  {
    id: 36,
    airline: "air dump",
    from: "lagos",
    to: "tokyo",
    date: "02 July 2025",
    departureTime: "15:30",
    arivalTime: "18:00",
    cheap: false,
    price: "3,100",
  },
  {
    id: 37,
    airline: "run airway",
    from: "lagos",
    to: "bankok",
    date: "25 June 2025",
    departureTime: "10:00",
    arivalTime: "14:15",
    cheap: true,
    price: "1,695",
  },
  {
    id: 38,
    airline: "air peace",
    from: "abuja",
    to: "bankok",
    date: "02 July 2025",
    departureTime: "20:00",
    arivalTime: "00:00",
    cheap: false,
    price: "1,300",
  },
  {
    id: 39,
    airline: "run airway",
    from: "abuja",
    to: "tokyo",
    date: "25 June 2025",
    departureTime: "11:45",
    arivalTime: "15:15",
    cheap: true,
    price: "1,300",
  },
  {
    id: 40,
    airline: "run airway",
    from: "abuja",
    to: "tokyo",
    date: "02 July 2025",
    departureTime: "01:15",
    arivalTime: "04:15",
    cheap: false,
    price: "4,300",
  },
  {
    id: 41,
    airline: "air dump",
    from: "lagos",
    to: "tokyo",
    date: "25 June 2025",
    departureTime: "18:45",
    arivalTime: "23:45",
    cheap: true,
    price: "1,300",
  },
  {
    id: 42,
    airline: "run airway",
    from: "lagos",
    to: "panama",
    date: "02 July 2025",
    departureTime: "13:00",
    arivalTime: "18:00",
    cheap: false,
    price: "4,300",
  },
  {
    id: 43,
    airline: "air peace",
    from: "abuja",
    to: "panama",
    date: "25 June 2025",
    departureTime: "21:15",
    arivalTime: "00:30",
    cheap: true,
    price: "2,500",
  },
  {
    id: 44,
    airline: "air dump",
    from: "abuja",
    to: "bankok",
    date: "02 July 2025",
    departureTime: "14:45",
    arivalTime: "17:00",
    cheap: false,
    price: "1,300",
  },
  {
    id: 45,
    airline: "air peace",
    from: "abuja",
    to: "panama",
    date: "25 June 2025",
    departureTime: "02:15",
    arivalTime: "06:15",
    cheap: true,
    price: "2,500",
  },
  {
    id: 46,
    airline: "run airway",
    from: "lagos",
    to: "panama",
    date: "02 July 2025",
    departureTime: "00:15",
    arivalTime: "04:45",
    cheap: false,
    price: "2,500",
  },
  {
    id: 47,
    airline: "air dump",
    from: "lagos",
    to: "bankok",
    date: "25 June 2025",
    departureTime: "09:45",
    arivalTime: "12:00",
    cheap: true,
    price: "4,300",
  },
  {
    id: 48,
    airline: "air dump",
    from: "abuja",
    to: "bali",
    date: "02 July 2025",
    departureTime: "16:45",
    arivalTime: "19:15",
    cheap: false,
    price: "1,300",
  },
  {
    id: 49,
    airline: "air dump",
    from: "lagos",
    to: "bankok",
    date: "25 June 2025",
    departureTime: "05:30",
    arivalTime: "10:30",
    cheap: true,
    price: "4,300",
  },
  {
    id: 50,
    airline: "run airway",
    from: "lagos",
    to: "bali",
    date: "02 July 2025",
    departureTime: "18:45",
    arivalTime: "21:00",
    cheap: false,
    price: "4,300",
  },
  {
    id: 51,
    airline: "air peace",
    from: "abuja",
    to: "tokyo",
    date: "25 June 2025",
    departureTime: "22:00",
    arivalTime: "23:30",
    cheap: true,
    price: "1,695",
  },
  {
    id: 52,
    airline: "air peace",
    from: "lagos",
    to: "bali",
    date: "02 July 2025",
    departureTime: "14:45",
    arivalTime: "16:15",
    cheap: false,
    price: "4,300",
  },
];

export const hotel = [
  {
    id: 1,
    name: "Dakka suits",
    location: "Bankok",
    price: 5000,
    stars: 4,
    img: "https://res.cloudinary.com/dzhhpr7f1/image/upload/v1750845625/fe72109e-632e-4cc1-8070-8aa0b16d0816_jqcbxg.jpg",
    address: "88 Sukhumvit Rd, Khlong Toei, Bangkok 10110, Thailand",
    about:
      "Dakka Suits offers a contemporary retreat in the heart of Bangkok with modern amenities and exceptional service. Guests enjoy spacious rooms, an on-site restaurant, and proximity to major shopping districts.",
    wifi: true,
    temperature: true,
    beds: 2,
    ac: true,
  },
  {
    id: 2,
    name: "Lorri suits",
    location: "Bankok",
    price: 3650,
    stars: 3,
    img: "https://res.cloudinary.com/dzhhpr7f1/image/upload/v1750845626/ff08a98d-2a32-4cb0-8bdd-bdbed91567f3_p4hk4k.jpg",
    address: "12 Charoen Krung Rd, Bang Rak, Bangkok 10500, Thailand",
    about:
      "Lorri Suits is a cozy mid-range hotel offering comfort and convenience. Located near Bangkok’s historic old town, it features clean, well-furnished rooms and a helpful staff ready to assist travelers.",
    wifi: true,
    temperature: true,
    beds: 1,
    ac: true,
  },
  {
    id: 3,
    name: "Hotel Transylvania",
    location: "Bankok",
    price: 5500,
    stars: 4,
    img: "https://res.cloudinary.com/dzhhpr7f1/image/upload/v1750845628/43a06fd7-06d3-466f-89e3-e031a4320cc6_vc6wtu.jpg",
    address: "99 Rama I Rd, Pathum Wan, Bangkok 10330, Thailand",
    about:
      "Hotel Transylvania offers luxury accommodations with a unique gothic-inspired theme. Guests can enjoy a rooftop pool, gourmet dining, and lavish interiors perfect for a memorable stay.",
    wifi: true,
    temperature: true,
    beds: 3,
    ac: true,
  },
  {
    id: 4,
    name: "Amoure suits",
    location: "Bankok",
    price: 3000,
    stars: 4,
    img: "https://res.cloudinary.com/dzhhpr7f1/image/upload/v1750845630/a004ca87-7bac-4b00-b5f5-c5108f87d59a_ogpm5l.jpg",
    address: "57 Phaya Thai Rd, Ratchathewi, Bangkok 10400, Thailand",
    about:
      "Amoure Suits is a romantic boutique hotel known for its intimate ambiance and elegant decor. Located near Bangkok’s vibrant nightlife, it’s perfect for couples and solo travelers.",
    wifi: true,
    temperature: true,
    beds: 2,
    ac: true,
  },
  {
    id: 5,
    name: "Edo Sakura",
    location: "Tokyo",
    price: 2700,
    stars: 4,
    img: "https://res.cloudinary.com/dzhhpr7f1/image/upload/v1750845525/IMG_2959_x2a2zc.jpg",
    address: "3 Chome-2-13 Shitaya, Taito City, Tokyo 110-0004, Japan",
    about:
      "Edo Sakura blends traditional Japanese hospitality with modern comforts. This ryokan-style hotel features tatami rooms, beautiful inner gardens, and easy access to Tokyo’s main attractions.",
    wifi: true,
    temperature: true,
    beds: 2,
    ac: true,
  },
  {
    id: 6,
    name: "The Peninsula",
    location: "Tokyo",
    price: 4200,
    stars: 4,
    img: "https://res.cloudinary.com/dzhhpr7f1/image/upload/v1750845526/IMG_2955_muxvel.jpg",
    address: "1-8-1 Yurakucho, Chiyoda City, Tokyo 100-0006, Japan",
    about:
      "The Peninsula Tokyo is a five-star hotel offering world-class luxury. Located near the Imperial Palace, it features elegant suites, fine dining, and a renowned spa experience.",
    wifi: true,
    temperature: true,
    beds: 3,
    ac: true,
  },
  {
    id: 7,
    name: "El Panama",
    location: "panama",
    price: 2900,
    stars: 3,
    img: "https://res.cloudinary.com/dzhhpr7f1/image/upload/v1750845530/IMG_2957_xveiuj.jpg",
    address: "Calle Eusebio A. Morales, Panama City, Panama",
    about:
      "El Panama Hotel offers comfort and convenience in the heart of Panama City. With a large pool, modern rooms, and close proximity to shopping and business centers, it’s ideal for both business and leisure travelers.",
    wifi: true,
    temperature: true,
    beds: 2,
    ac: true,
  },
  {
    id: 8,
    name: "Hotel magjaha",
    location: "panama",
    price: 1220,
    stars: 4,
    img: "https://res.cloudinary.com/dzhhpr7f1/image/upload/v1750845529/IMG_2956_mcvn9k.jpg",
    address: "Ave. Balboa, Bella Vista, Panama City, Panama",
    about:
      "Hotel Magjaha is a budget-friendly hotel offering great value for travelers. Enjoy clean rooms, friendly service, and a convenient location close to the city’s waterfront and restaurants.",
    wifi: true,
    temperature: true,
    beds: 1,
    ac: true,
  },
  {
    id: 9,
    name: "The Apurva Kempinski",
    location: "bali",
    price: 5300,
    stars: 5,
    img: "https://res.cloudinary.com/dzhhpr7f1/image/upload/v1750845527/IMG_2958_cxgcae.jpg",
    address: "Jalan Raya Nusa Dua Selatan, Benoa, Bali 80361, Indonesia",
    about:
      "The Apurva Kempinski Bali offers a breathtaking luxury experience with panoramic ocean views, stunning architecture, and impeccable service. It's perfect for honeymooners and luxury seekers.",
    wifi: true,
    temperature: true,
    beds: 3,
    ac: true,
  },
  {
    id: 10,
    name: "AYANA Resort & Spa",
    location: "bali",
    price: 3100,
    stars: 4,
    img: "https://res.cloudinary.com/dzhhpr7f1/image/upload/v1750845527/IMG_2960_p9ck4h.jpg",
    address: "Karang Mas Estate, Jimbaran, Bali 80364, Indonesia",
    about:
      "AYANA Resort & Spa is a world-renowned luxury resort in Bali featuring oceanfront villas, private beaches, award-winning restaurants, and world-class spa services. Ideal for a serene escape.",
    wifi: true,
    temperature: true,
    beds: 2,
    ac: true,
  },
];
